Prepare endpoint and service integrations for accepting hacker applications
HackAtUCI/HackUCI-Site pull request #30
Opened 2023-01-04 01:57 UTC by njhuey

Create an API endpoint /user/apply to accept a hacker application

- Perform any necessary data validation
- Upload the applicant's resume to Google Drive
- Store the application data in MongoDB
- Send a confirmation email to the applicant

2023-01-04 02:50 UTC, taesungh requested changes
Thanks for pulling this together and familiarizing yourself with the other services. We have the concept down but could improve some of the internals.

2023-01-09 08:21 UTC, rileysw approved these changes

2023-01-09 08:31 UTC, samderanova approved these changes

2023-01-09 08:33 UTC, taesungh approved these changes

2023-01-09 08:33 UTC, merged