Add intro section
HackAtUCI/HackUCI-Site pull request #40
Opened 2023-01-11 04:26 UTC by jason-zenarosa

https://github.com/HackAtUCI/HackUCI-Site/issues/18

2023-01-11 21:48 UTC, samderanova requested changes

2023-01-12 02:41 UTC, RandyHuynh5815 requested changes

2023-01-12 05:49 UTC, samderanova approved these changes

2023-01-12 05:50 UTC, RandyHuynh5815 reviewed
Resolve prettier issues

2023-01-12 05:58 UTC, RandyHuynh5815 approved these changes

2023-01-12 05:58 UTC, merged