Implement basic logout endpoint
HackAtUCI/HackUCI-Site pull request #60
Opened 2023-01-12 20:17 UTC by taesungh

Clear user identity cookie to log user out. Couldn't figure out how to use server-side rendering to set cookie and redirect at the same time while also working when approaching from Navigation.

2023-01-12 23:23 UTC, samderanova requested changes
Nice work on this! Just had one small question.

2023-01-13 21:44 UTC, taesungh commented on src/api/routers/user.py
> +    return response
The user identity is removed by setting the auth cookie of the response as empty. I suppose we could add a response parameter to mutate, but then we would need to use the `response_class` parameter on the path decorator to actually serve a redirect. I suppose it's a matter of style.

2023-01-13 23:55 UTC, samderanova approved these changes

2023-01-14 00:06 UTC, njhuey approved these changes

2023-01-14 00:15 UTC, merged