added stickermule sponsor
HackAtUCI/HackUCI-Site pull request #77
Opened 2023-01-17 01:16 UTC by Pegysus

- Added Stickermule logo and link to their website in a Sponsor section
- Added information for other sponsors in sponsors.json but still have yet to implement their links on the section

2023-01-17 18:40 UTC, rileysw commented
This is a temporary solution since the deadline to publish the Sticker Mule logo is by Wednesday morning. The temporary design implementation (as well as the data in sponsors.json) was approved by Parsa.

I think both @Pegysus and me were confused about using the image relative paths from sponsors.json since it wouldn't load correctly into the image component.

2023-01-18 00:17 UTC, taesungh reviewed
Few more things to address, I'm working on most of them.

2023-01-18 00:17 UTC, taesungh commented on src/views/home/sections/Sponsors/Sponsors.tsx
> +		<Link href={props.data.url}>
Suggestion: `next/link` should be used only for internal routing, not to link to external sites.

2023-01-18 00:17 UTC, taesungh commented on src/views/home/sections/Sponsors/Sponsors.module.scss
> +}
Suggestion: specifiers can be nested with SASS.

2023-01-18 00:24 UTC, taesungh commented on src/views/home/sections/Sponsors/Sponsors.tsx
> +function SponsorItem(props: any) {
`SponsorItemProps` added in 0511137.

2023-01-18 06:18 UTC, taesungh commented on src/views/home/sections/Sponsors/Sponsors.tsx
> +				to learn more about our event! For more information, please email us
Suggestion: use of word "information" seems a little redundant/conflicting. Perhaps say "For additional inquiries" in second sentence.

2023-01-19 06:28 UTC, samderanova requested changes
Thanks for working on this! Just have one small suggestion.

2023-01-19 06:28 UTC, samderanova commented on src/views/home/sections/Sponsors/Sponsors.tsx
> +			</p>
Nitpick: We should center the paragraph element and change the color of the link to something other than blue (perhaps same orange as the link in the footer) for consistency.

2023-01-19 06:28 UTC, samderanova commented on src/views/home/sections/Sponsors/Sponsors.tsx
> +				</Col>
Awesome animation!

2023-01-19 19:02 UTC, taesungh commented
Please fix the formatting/linting errors rather than dismissing them.

2023-01-20 18:38 UTC, samderanova approved these changes

2023-01-20 18:39 UTC, taesungh approved these changes
Thanks for starting this. Temporary solution works for now; we'll clean up more later.

2023-01-20 18:42 UTC, merged