Add starter packs to resources page
HackAtUCI/HackUCI-Site pull request #88
Opened 2023-01-29 18:44 UTC by samderanova

- Update navigation bar with new route to resources
- Add icons for each type of starter pack, following the design from graphics

2023-01-29 18:48 UTC, samderanova commented on src/assets/data/resources.json
> +]
Uhh anyone have any idea what this means?

2023-01-30 07:24 UTC, rileysw commented on src/assets/data/resources.json
> +]
The two files are the same on my end 😩

2023-02-02 02:43 UTC, taesungh commented on src/assets/data/resources.json
> +]
Could be your line endings, i.e. CRLF vs LF

2023-02-03 05:48 UTC, rileysw submitted a review, later dismissed

2023-02-03 19:17 UTC, taesungh requested changes
Looks mostly good, small issue on the hover transition.

2023-02-03 19:17 UTC, taesungh commented on src/views/resources/Resource/Resource.tsx
> +					style={{ textDecoration: "none" }}
Thought [non-blocking]: using button styles might make this simpler, but I don't want to think about it right now.

2023-02-03 19:17 UTC, taesungh commented on src/views/resources/Resources.tsx
> +import tools from "assets/icons/tools.svg";
Note: for future reference, might be nice to include the source of these icon assets as part of the commit message body.

2023-02-03 22:43 UTC, RandyHuynh5815 commented on src/views/resources/Resource/Resource.tsx
> +	const target = useRef(null);
It's used in the a element within the OverlayTrigger.

2023-02-04 00:58 UTC, taesungh commented on src/views/resources/Resource/Resource.module.scss
> +		transition: 0.25s ease;
@RandyHuynh5815, we should also constrain the transition property

2023-02-04 01:56 UTC, lassenordahl commented
This site is lovely! I have one request. Could you update the CockroachDB link to:

https://www.cockroachlabs.com/docs?utm_source=hackuci2023&utm_medium=event&utm_campaign=hackathon

so we could do some cross domain tracking for Hackathon users? That would be awesome.

2023-02-04 02:13 UTC, samderanova commented on src/views/resources/Resource/Resource.tsx
> +	const target = useRef(null);
^^

2023-02-04 02:30 UTC, taesungh commented on src/views/resources/Resources.tsx
> +};
@RandyHuynh5815, this is a bit more complicated than I was expecting, but it will work for now.

2023-02-04 02:34 UTC, taesungh submitted a review, later dismissed
Checks workflow didn't run since there are merge conflicts, but functionality alright :/

2023-02-04 02:41 UTC, njhuey approved these changes, later dismissed

2023-02-04 02:41 UTC, njhuey commented on src/views/resources/Resource/Resource.tsx
> +import { useRef } from "react";
Unused import

2023-02-04 02:48 UTC, njhuey approved these changes

2023-02-04 02:48 UTC, taesungh approved these changes

2023-02-04 02:48 UTC, merged